//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Billings = new HashSet<Billing>();
        }
    
        public int Id { get; set; }
        public string IBAN { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<System.DateTime> Startdate { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> ClientId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Type Type { get; set; }
        public virtual ICollection<Billing> Billings { get; set; }
    }
}
