//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Accounts = new HashSet<Account>();
            this.Banks = new HashSet<Bank>();
        }
    
        public int Id { get; set; }
        public string Firstnme { get; set; }
        public string Lastname { get; set; }
        public string CNP { get; set; }
        public string Mobile { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string Number { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<Bank> Banks { get; set; }
    }
}
