//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Banks = new HashSet<Bank>();
            this.UserActions = new HashSet<UserAction>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Mobile { get; set; }
        public string Mail { get; set; }
        public Nullable<int> RoleId { get; set; }
    
        public virtual ICollection<Bank> Banks { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<UserAction> UserActions { get; set; }
    }
}
